import scala.collection.mutable._

object ArrayStackTester extends App{
  println("======= Array Stack =========")
  var arrayStack = ArrayStack[Double]()
  arrayStack.push(1.0)
  arrayStack.push(4.5)
  arrayStack.push(5.6)
  arrayStack.push(3.4)
  arrayStack.foreach((x: Double) => print(x + " "))
  println()
  println(arrayStack.pop())
  println(arrayStack.pop())
  println(arrayStack.pop())
  println(arrayStack.top)
  println(arrayStack.pop())
  println("======== My Array Stack =======")
  var myArrayStack = MyArrayStack[Double]()
  myArrayStack.push(1.0)
  myArrayStack.push(4.5)
  myArrayStack.push(5.6)
  myArrayStack.push(3.4)
  myArrayStack.foreach((x: Double) => print(x + " "))
  println()
  println(myArrayStack.pop())
  println(myArrayStack.pop())
  println(myArrayStack.pop())
  println(myArrayStack.top)
  println(myArrayStack.pop())
}
